# This is done in a separate workflow because pull_request workflow cannot write comments from forks.
# This is inspired from various pr-comment jobs in the ruff repo https://github.com/astral-sh/ruff/tree/main/.github/workflows
# See also https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks
name: Django Test Suite PR comment

on:
  workflow_run:
    workflows: [Python]
    types: [completed]
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: The ecosystem workflow that triggers the workflow run
        required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: dawidd6/action-download-artifact@v11
        name: Download pull request number
        with:
          name: pr-number
          run_id: ${{ github.event.workflow_run.id ||  github.event.inputs.workflow_run_id }}
          if_no_artifact_found: ignore
          allow_forks: true

      - name: Parse pull request number
        id: pr-number
        run: |
          if [[ -f pr-number ]]
          then
            echo "pr-number=$(<pr-number)" >> "$GITHUB_OUTPUT"
          fi

      - uses: dawidd6/action-download-artifact@v11
        name: "Download Django test suite results"
        id: download-ecosystem-result
        if: steps.pr-number.outputs.pr-number
        with:
          name: test-diff-result
          workflow: python.yaml
          pr: ${{ steps.pr-number.outputs.pr-number }}
          workflow_conclusion: completed
          if_no_artifact_found: ignore
          allow_forks: true

      - name: Skip symlinks
        if: steps.download-ecosystem-result.outputs.found_artifact == 'true'
        run: |
          // Guard against malicious ecosystem results that symlink to a secret
          // file on this runner
          if [[ -L test-diff-result ]]
          then
              echo "Error: test-diff-result cannot be a symlink"
              exit 1
          fi

      - name: Find existing comment
        uses: peter-evans/find-comment@v3
        if: steps.generate-comment.outcome == 'success'
        id: find-comment
        with:
          issue-number: ${{ steps.pr-number.outputs.pr-number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- generated-comment ecosystem -->"

      - name: Create or update comment
        if: steps.find-comment.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ steps.pr-number.outputs.pr-number }}
          body-path: test-diff-result
          edit-mode: replace
